FROM 162230498103.dkr.ecr.eu-west-1.amazonaws.com/mutable-rust-ci:latest-deb11 AS builder
WORKDIR /usr/src/app
COPY . ./
RUN git describe --tags --always && git status
RUN cargo build --workspace --release
RUN mkdir /usr/src/bin && for file in ls ${CARGO_TARGET_DIR:-./target}/release/*; do if test -f $file -a -x $file; then cp $file /usr/src/bin; fi; done

FROM debian:bullseye-slim
COPY ci/use-debian-archive.sh /use-debian-archive.sh
RUN /use-debian-archive.sh \
    && apt-get upgrade --yes \
    && apt autoremove --yes \
    && rm -rf /var/lib/apt/lists/* /use-debian-archive.sh
COPY --from=builder /usr/src/bin/* /usr/local/bin/
