FROM 162230498103.dkr.ecr.eu-west-1.amazonaws.com/mutable-rust-ci:latest-deb13 AS builder
WORKDIR /usr/src/app
COPY . ./
RUN git describe --tags --always && git status
RUN cargo build --workspace --release
RUN mkdir /usr/src/bin && \
	for file in "${CARGO_TARGET_DIR:-./target}"/release/*; do \
		if test -f "$file" -a -x "$file"; then \
			cp "$file" /usr/src/bin; \
		fi; \
	done

FROM debian:trixie-slim
ENV DEBIAN_FRONTEND=noninteractive
ENV APT_LISTCHANGES_FRONTEND=none
RUN apt-get update \
    && apt-get upgrade --yes \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/* /tmp/* /var/tmp/*
COPY --from=builder /usr/src/bin/* /usr/local/bin/
